spring:
  # 配置數據源信息
  datasource:
    # 配置數據源類型,使用SpringBoot3 預設的連接持數據源,hikari
    type: com.zaxxer.hikari.HikariDataSource
    # 配置連接數據庫的各個信息
    driver-class-name: org.mariadb.jdbc.Driver
    # 配置URL,mysql8.0剛出時不配置?serverTimezone=Asia/Taipei,會報啟動錯誤
    # 現在好像解決了
    url: jdbc:mariadb://192.168.56.1:3306/topbs2025_international_conferenct?rewriteBatchedStatements=true
    # 配置連接用戶
    username: root
    # 配置用戶密碼
    password: kamikazey0022
      
    
#minio 分布式文件儲存服務,因為沒有實現的starter所以這邊配置主要是獲取屬性值而已
minio:
  #minio服務所在地址,這個指的是server不是控制台
  endpoint: http://192.168.56.1:9000
  #預設儲存桶名稱,這是為了避免上傳時沒選定Bucket造成錯誤
  bucketName: topbs2025
  #訪問的key,預設是帳號,除非有去特別設置Access key
  accessKey: admin
  #訪問的密鑰,預設是密碼,除非有去特別設置Access key
  secretKey: joey880522
  
# Redisson配置,需要搭配Config配置類使用,
# 不使用全部使用yml自動配置是因為,當今天有需要業務redis , 分布式鎖redis , redis 集群之類的,手動配置更好實現
redisson:
  address: "redis://192.168.56.1:6379"
#  password: "yourpassword"  # 如果有密码的话
  database: 0
    